### PR TITLE
Optionally require `forwardable`

### LINKED ISSUE #29: Issue with generative command
Hey,

I am getting the following error while trying to run `generative` command:
```
▶ generative
/Users/danielbarreto/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/generative-0.2.4/lib/generative.rb:8:in `singleton class': uninitialized constant #<Class:Generative>::Forwardable (NameError)
        from /Users/danielbarreto/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/generative-0.2.4/lib/generative.rb:7:in `<module:Generative>'
        from /Users/danielbarreto/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/generative-0.2.4/lib/generative.rb:3:in `<top (required)>'
        from /Users/danielbarreto/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/danielbarreto/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/danielbarreto/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/generative-0.2.4/bin/generative:5:in `<top (required)>'
        from /Users/danielbarreto/.rbenv/versions/2.3.3/bin/generative:22:in `load'
        from /Users/danielbarreto/.rbenv/versions/2.3.3/bin/generative:22:in `<main>'
```

My current project can be found at this [repo](https://github.com/danielfsbarreto/property-based-tests/tree/generative). Is there something I am doing wrong? I did not find anything on the README. As far as I understood, it should magically work. 😄 

However, setting up `GENERATIVE_COUNT` manually seems to be functioning as expected:
```
▶ GENERATIVE_COUNT=10_000 bundle exec rspec spec/calculator_spec.rb

Calculator
  #add
    returns the sum of its arguments
    sums positive and negative values
    does nothing if sums value with zero
    left identity property (generative)
      example at ./spec/calculator_spec.rb:22
    right identity property (generative)
      example at ./spec/calculator_spec.rb:28
    commutativity property (generative)
      example at ./spec/calculator_spec.rb:35
    associativity property (generative)
      example at ./spec/calculator_spec.rb:43

Finished in 3.6 seconds (files took 0.08446 seconds to load)
40003 examples, 0 failures
```

### PR DESCRIPTION
**Pull request by levionessa**
Newer versions of Ruby moved `Forwardable`
into a `forwardable` module.

Hey @justincampbell if you have a change to take a peek please do. If not I'll probably go ahead and merge in the next day or so.

Fixes #29

### CODE REVIEW

**Comment by justincampbell** [comment]
This makes sense! But I don't understand the `if RUBY_DESCRIPTION` part. Is that supposed to be matched against something?

File: lib/generative.rb [hunk 1]
```diff
@@ -1,4 +1,7 @@
 require 'rspec/core'
+if RUBY_DESCRIPTION
+  require 'forwardable'
+end
```
Comment (justincampbell) [inline lib/generative.rb]: I think it would be safe to just `require 'forwardable'` without looking at the Ruby description/version

Comment (levionessa) [inline lib/generative.rb]: :cool:

**Comment by levionessa** [comment]
`RUBY_DESCRIPTION` was added in 2.3 for the full Ruby version. I *thought* that we'd have errors in < 2.3 with the require. TIL it doesn't!

**Comment by justincampbell** [comment]
Cool, thanks for updating!
